### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by YKingslayer** [BacooTang/huya-danmu#9]
大佬，小弟初看到你写的huya-danmu，非常震惊。但是你既然弹幕消息都可以获取到，为啥发送弹幕的用户头像没有一并获取呢？难道说难度系数很高，特别想获取用户头像，还有礼物头像数据

**Comment by YKingslayer** [comment]
@BacooTang

**Comment by BacooTang** [comment]
因为我当初只为我自己项目的需求来写的，所以没有做别的,我也只是抛砖引玉，写成大概的思路，需要的自己改改就好了，没啥难度，加油，我这是不打算更新了的
